# You can replace repo-name with your Azure Container Registry repository name 
# and ${{ secrets.ACR_REGISTRY }}, ${{ secrets.ACR_USERNAME }}, 
# and ${{ secrets.ACR_PASSWORD }} with your Azure Container Registry credentials. 
# You can also replace aci-dns-label, eastus, and aci-resource-group with your desired values.
# Make sure you have created an Azure Container Instance resource group 
# and have set up the necessary credentials in your GitHub repository secrets.

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/repo-name:${{ github.sha }}
      - name: Login to Azure Container Instance
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          image-name: ${{ secrets.ACR_REGISTRY }}/repo-name:${{ github.sha }}
          dns-name-label: aci-dns-label
          location: eastus
          resource-group: aci-resource-group